# Kafka Streams Configuration
kafka.application.id=streaming-app
kafka.bootstrap.servers=localhost:9092,localhost:9093
kafka.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
kafka.default.value.serde=io.confluent.kafka.streams.serdes.avro.GenericAvroSerde
kafka.schema.registry.url=http://localhost:8081

# Stream Processing Configuration
kafka.processing.guarantee=at_least_once
kafka.commit.interval.ms=10000
kafka.num.stream.threads=1

# Application Configuration
coinbase.topic.name=coinbase_BTC-USD
coinbase.source.name=Coinbase
schema.registry.url=http://localhost:8081
