FROM python:3.12-slim

# Zet werkdirectory
WORKDIR /app

# Kopieer alleen wat nodig is voor installatie (betere caching)
COPY ../pyproject.toml .
COPY ../src/ ./src
COPY ../.env .env

# Installeer afhankelijkheden via pip (hatch + pyproject.toml)
RUN pip install --upgrade pip && pip install .

# Zet PYTHONPATH zodat src importeerbaar is
ENV PYTHONPATH=/app/src
ENV PYTHONUNBUFFERED=1
ENV IN_DOCKER=1
# Start de app
CMD ["python", "src/producers/coinbase_producer/main.py"]
